# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: node:8.7.0
      
      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/mongo:3.4.4

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run: npm install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
        
      # run tests!
      - run: npm test
      
  
  deploy:
    docker:
      # specify the version you desire here
      - image: node:8.7.0

    steps:
      - checkout
      
      # deploy docker hub build
      - run: curl -H "Content-Type: application/json" --data '{"build": true}' -X https://registry.hub.docker.com/u/rynepuffer/node-demoapp/trigger/512abd90-a78a-43d5-9914-db6e2cc7e552/
      
